# version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth_service:
    build: ./auth_service
    restart: always
    command: python app.py
    volumes:
      - ./auth_service:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URI: postgresql://postgres:password@db:5432/ecommerce
      JWT_SECRET_KEY: super-secret-key
  product_service:
    build: ./product_service
    restart: always
    volumes:
      - ./product_service:/app
    ports:
      - "5001:5000"  # host:container
    depends_on:
      - db
    environment:
      DATABASE_URI: postgresql://postgres:password@db:5432/ecommerce
      FLASK_ENV: development

volumes:
  postgres_data:
